// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0Ux8glsY6bf2ZoCtNoBOfFfi264WqEWA',
    appId: '1:938588039633:web:ed8223f37434c397db58f0',
    messagingSenderId: '938588039633',
    projectId: 'todoaholic-2671e',
    authDomain: 'todoaholic-2671e.firebaseapp.com',
    storageBucket: 'todoaholic-2671e.appspot.com',
    measurementId: 'G-VEJRSBPT15',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqEMQJtBqYTRVjTMWrlIo1A9tMq9JXYiA',
    appId: '1:938588039633:android:569fed055faa2718db58f0',
    messagingSenderId: '938588039633',
    projectId: 'todoaholic-2671e',
    storageBucket: 'todoaholic-2671e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBid2K8FbCtb1rIyGrEl5Bzfmd2qErbDxo',
    appId: '1:938588039633:ios:2c6ad703dfe10d21db58f0',
    messagingSenderId: '938588039633',
    projectId: 'todoaholic-2671e',
    storageBucket: 'todoaholic-2671e.appspot.com',
    iosClientId: '938588039633-0uan54q360ikh2fbcde5ek48u0s5bocc.apps.googleusercontent.com',
    iosBundleId: 'com.andordavoti.todoaholic',
  );
}
